# This workflow will install Python dependencies, run flake8 & pytest with multiple versions of Python

name: Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install twine
    - name: Build sdist
      run: |
        python setup.py sdist
        python -m twine upload --repository testpypi -u __token__ -p ${{ secrets.API_V5_PYPI_TOKEN }} dist/*
